(hall-description
  (name "monads")
  (prefix "")
  (version "0.1")
  (author "Silas Vedder")
  (copyright (2022))
  (synopsis "")
  (description "")
  (home-page "https://github.com/silasfox/guile-monads")
  (license gpl3+)
  (dependencies `())
  (files (libraries
           ((scheme-file "monads") (directory "monads" ())))
         (tests ((directory "tests" ())))
         (programs ((directory "scripts" ())))
         (documentation
           ((org-file "README")
            (symlink "README" "README.org")
            (text-file "HACKING")
            (text-file "COPYING")
            (directory "doc" ((texi-file "monads")))))
         (infrastructure
           ((scheme-file "guix")
            (text-file ".gitignore")
            (scheme-file "hall")))))
